# get slack-token on website https://api.slack.com/apps/
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  slack-token: "xoxb-6491523158274-6491712597826-jwrPzRYLGRyluX8dvkvlNLbV"
